---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - {{.Data.ip_range_start}}-{{.Data.ip_range_end}}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: mpc
  namespace: metallb-system